/*
 Navicat Premium Data Transfer

 Source Server         : localhost_3306
 Source Server Type    : MySQL
 Source Server Version : 80300 (8.3.0)
 Source Host           : localhost:3306
 Source Schema         : credit_report_service

 Target Server Type    : MySQL
 Target Server Version : 80300 (8.3.0)
 File Encoding         : 65001

 Date: 26/09/2024 17:44:59
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `credit` decimal(10,2) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1001 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ----------------------------
-- Records of users
-- ----------------------------
BEGIN;
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (1, 'Valerie Ellis', 498.25);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (2, 'Lu Rui', 647.40);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (3, 'Sano Kenta', 738.32);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (4, 'Koyama Riku', 187.75);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (5, 'Gao Zitao', 52.21);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (6, 'Doris Price', 707.69);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (7, 'Yung Ka Man', 465.13);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (8, 'Chiang Chi Yuen', 192.15);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (9, 'Ogawa Itsuki', 281.28);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (10, 'Ng Suk Yee', 390.05);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (11, 'Takagi Tsubasa', 245.00);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (12, 'Zhao Xiaoming', 439.21);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (13, 'Miyamoto Mio', 197.69);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (14, 'Rosa Price', 917.54);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (15, 'Carl Rice', 116.30);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (16, 'Dai Sau Man', 826.02);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (17, 'Sean Coleman', 982.72);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (18, 'Yu Zitao', 32.99);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (19, 'Xie Lan', 346.17);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (20, 'Hazel Moore', 718.96);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (21, 'Chen Xiuying', 809.94);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (22, 'Meng Yu Ling', 727.96);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (23, 'Lok Ming', 147.99);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (24, 'Dai Zhiyuan', 567.03);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (25, 'Kwok Kwok Ming', 637.27);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (26, 'Murata Yamato', 542.02);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (27, 'Lu Ziyi', 532.29);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (28, 'Kong Ka Fai', 531.44);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (29, 'Luo Ziyi', 668.60);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (30, 'Lok Tin Lok', 913.57);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (31, 'Margaret Morris', 235.69);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (32, 'Inoue Akina', 400.84);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (33, 'Doris Kennedy', 726.47);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (34, 'Leroy Hamilton', 904.85);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (35, 'Miu Ka Ming', 656.54);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (36, 'Wada Mai', 30.33);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (37, 'Matsumoto Seiko', 62.19);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (38, 'Hui Kwok Yin', 165.95);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (39, 'Tao Rui', 997.10);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (40, 'Huang Lan', 972.23);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (41, 'Roy Kelley', 899.07);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (42, 'Fujii Takuya', 292.77);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (43, 'Ng Yu Ling', 532.09);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (44, 'Murata Nanami', 836.51);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (45, 'Kondo Yuto', 350.93);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (46, 'Fung Chiu Wai', 218.30);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (47, 'Cheung On Kay', 702.56);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (48, 'Inoue Hikari', 590.06);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (49, 'Takada Yuna', 60.40);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (50, 'Iwasaki Seiko', 877.78);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (51, 'Shi Zitao', 646.76);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (52, 'Cheng Xiaoming', 714.20);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (53, 'Nomura Ikki', 672.21);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (54, 'Pang On Na', 770.69);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (55, 'Pan Rui', 630.85);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (56, 'Hao Jiehong', 771.64);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (57, 'Ku Hok Yau', 733.29);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (58, 'Shen Jialun', 191.43);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (59, 'Mo Suk Yee', 101.78);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (60, 'Ng Sum Wing', 628.16);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (61, 'Chen Yunxi', 190.66);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (62, 'Kono Yuto', 133.81);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (63, 'Ruby Myers', 753.42);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (64, 'Chang On Kay', 242.63);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (65, 'Kudo Kaito', 558.78);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (66, 'Jia Xiuying', 815.82);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (67, 'Jin Zhiyuan', 258.41);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (68, 'Eleanor Hawkins', 183.29);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (69, 'Guo Zitao', 19.57);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (70, 'Man Chung Yin', 52.95);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (71, 'Irene Hicks', 390.23);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (72, 'Nakayama Hazuki', 178.82);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (73, 'Edith Ferguson', 894.12);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (74, 'Mo Lan', 485.74);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (75, 'Hsuan Wing Sze', 728.47);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (76, 'Chen Shihan', 315.21);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (77, 'Yamashita Hana', 40.42);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (78, 'Kathleen Perez', 96.21);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (79, 'Murakami Kasumi', 382.80);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (80, 'Tian Lan', 661.14);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (81, 'Willie Fox', 677.54);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (82, 'Zhu Zhiyuan', 214.64);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (83, 'Fujiwara Yuto', 951.14);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (84, 'Yu Jiehong', 661.33);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (85, 'Kam Ming Sze', 344.83);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (86, 'Sakurai Mio', 59.51);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (87, 'Susan Robertson', 58.97);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (88, 'Xu Lan', 139.88);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (89, 'Zhao Rui', 498.04);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (90, 'Takahashi Eita', 980.34);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (91, 'Liao Jiehong', 584.93);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (92, 'Sheh Lai Yan', 447.89);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (93, 'Kong Xiuying', 741.11);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (94, 'Gao Shihan', 946.61);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (95, 'Jerry Gray', 596.66);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (96, 'Tse Ka Ming', 929.61);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (97, 'Marie Marshall', 388.09);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (98, 'Han Chun Yu', 371.32);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (99, 'Melissa Herrera', 125.64);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (100, 'Richard Soto', 693.12);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (101, 'Lam Wing Fat', 870.37);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (102, 'Nakamura Yuto', 543.61);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (103, 'Sakurai Minato', 856.24);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (104, 'Xiong Xiaoming', 33.29);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (105, 'Long Shihan', 349.55);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (106, 'Qiu Zhennan', 20.06);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (107, 'Bonnie Washington', 53.40);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (108, 'Hu Zitao', 913.12);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (109, 'Matsumoto Yamato', 212.28);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (110, 'Cynthia West', 123.55);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (111, 'Ishikawa Rena', 6.31);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (112, 'Timothy Miller', 601.68);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (113, 'Kam Chung Yin', 709.08);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (114, 'Louise Ortiz', 331.39);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (115, 'Han Lai Yan', 156.95);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (116, 'Mario Ross', 543.30);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (117, 'Li Lu', 349.92);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (118, 'Fujita Shino', 343.38);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (119, 'Yu Zhennan', 179.78);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (120, 'Edna Cruz', 65.96);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (121, 'Chan Ka Man', 379.30);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (122, 'Ku Hok Yau', 863.23);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (123, 'Lawrence Robertson', 500.13);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (124, 'Fujii Ikki', 866.94);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (125, 'Fu Wing Fat', 817.94);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (126, 'Pan Shihan', 874.83);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (127, 'Tracy Murray', 827.01);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (128, 'Okada Itsuki', 58.80);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (129, 'Kwong Kwok Kuen', 777.91);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (130, 'Kyle Nguyen', 660.10);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (131, 'Pamela Owens', 681.19);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (132, 'Xie Xiuying', 342.74);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (133, 'Lui Tak Wah', 760.30);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (134, 'Chang Wai Man', 984.80);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (135, 'Au Kwok Wing', 626.03);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (136, 'Gerald Thomas', 722.91);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (137, 'Murakami Kaito', 5.53);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (138, 'Joel Miller', 845.14);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (139, 'Heung Kwok Ming', 361.80);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (140, 'Fu Zhennan', 576.94);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (141, 'Maria Hicks', 32.00);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (142, 'Pamela Turner', 45.90);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (143, 'Ishida Kaito', 27.35);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (144, 'Shi Xiuying', 871.34);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (145, 'Wang Zhiyuan', 108.16);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (146, 'Takeuchi Yuna', 855.00);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (147, 'Yin Hiu Tung', 706.23);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (148, 'Lau Ting Fung', 958.89);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (149, 'Chan On Kay', 468.24);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (150, 'Timothy Gray', 536.34);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (151, 'Eleanor Alexander', 464.67);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (152, 'Kwan Kwok Kuen', 367.85);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (153, 'Hou Lu', 163.32);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (154, 'Joseph Myers', 530.36);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (155, 'Jacqueline Powell', 442.99);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (156, 'Randall Jenkins', 421.79);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (157, 'Lu Zhiyuan', 255.08);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (158, 'Qian Zitao', 400.52);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (159, 'Mario Hunt', 889.34);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (160, 'Inoue Kenta', 73.32);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (161, 'Abe Sakura', 594.51);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (162, 'Wu Anqi', 859.69);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (163, 'Takahashi Hikari', 978.66);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (164, 'Xie Yuning', 873.70);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (165, 'Xiao Jialun', 339.02);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (166, 'Murata Hazuki', 130.67);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (167, 'Mui Wing Fat', 634.15);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (168, 'Qian Zhennan', 686.24);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (169, 'Walter Vasquez', 697.23);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (170, 'Mo Yuning', 436.32);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (171, 'Xue Zhiyuan', 97.88);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (172, 'Ethel Jones', 480.72);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (173, 'Miu Suk Yee', 149.45);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (174, 'Watanabe Kasumi', 826.81);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (175, 'Anita Thompson', 375.64);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (176, 'Tin Chiu Wai', 790.23);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (177, 'Yin Lan', 808.43);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (178, 'Yamashita Takuya', 945.41);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (179, 'Ono Daisuke', 544.01);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (180, 'Wong Tin Wing', 536.54);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (181, 'Yan Shihan', 778.65);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (182, 'Hara Akina', 577.40);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (183, 'Lu Shihan', 590.80);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (184, 'Gladys Olson', 439.87);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (185, 'Ishida Yota', 990.26);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (186, 'Lau Ka Ming', 103.12);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (187, 'Lei Ziyi', 306.49);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (188, 'Zheng Ziyi', 153.47);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (189, 'Luo Zhiyuan', 401.07);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (190, 'He Zhiyuan', 571.69);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (191, 'Mo Ka Keung', 450.14);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (192, 'Tian Jiehong', 111.86);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (193, 'Anthony Webb', 803.33);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (194, 'Jiang Shihan', 205.16);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (195, 'Kwong Ka Ming', 966.26);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (196, 'Jane Wells', 287.55);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (197, 'Fan Sze Yu', 10.84);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (198, 'Chu Chi Yuen', 910.78);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (199, 'Chan Siu Wai', 347.19);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (200, 'Nakano Hikaru', 34.71);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (201, 'Morita Ren', 830.09);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (202, 'Ng Kwok Yin', 487.62);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (203, 'Kam Fu Shing', 830.58);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (204, 'Ono Ayano', 338.55);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (205, 'Cheung Wai Yee', 573.85);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (206, 'Shen Anqi', 893.37);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (207, 'Lee Kwok Yin', 541.87);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (208, 'Matsumoto Hikari', 857.30);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (209, 'Dorothy Watson', 322.31);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (210, 'Jin Lu', 635.48);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (211, 'Yuen Tin Lok', 560.77);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (212, 'Earl Murray', 903.01);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (213, 'Charles Soto', 579.64);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (214, 'Donald Soto', 953.84);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (215, 'Mo Ziyi', 87.54);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (216, 'Tong Ling Ling', 114.60);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (217, 'Siu Tin Lok', 201.40);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (218, 'Harada Ayato', 810.57);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (219, 'Sano Eita', 560.45);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (220, 'Liao Lu', 699.66);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (221, 'Yang Xiaoming', 677.04);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (222, 'Elaine Tucker', 933.79);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (223, 'Connie Moore', 987.68);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (224, 'Lu Yunxi', 565.73);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (225, 'Okada Yuto', 531.34);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (226, 'Ishii Hikari', 718.88);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (227, 'Shen Rui', 496.68);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (228, 'Luo Xiuying', 470.87);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (229, 'Choi Chiu Wai', 488.14);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (230, 'Qian Shihan', 953.15);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (231, 'Nakamura Hikaru', 988.82);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (232, 'He Yunxi', 893.69);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (233, 'Rosa Burns', 316.05);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (234, 'Chic Wing Fat', 629.68);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (235, 'Ng Sum Wing', 515.16);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (236, 'Tsang Hui Mei', 242.79);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (237, 'Meng Wing Sze', 881.79);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (238, 'Clara Gray', 263.20);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (239, 'Aoki Yuto', 669.24);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (240, 'Kathy Boyd', 334.16);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (241, 'Bryan Fisher', 673.51);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (242, 'Koon Fu Shing', 789.80);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (243, 'Wong Wing Fat', 949.82);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (244, 'Inoue Ikki', 87.22);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (245, 'Watanabe Mio', 452.77);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (246, 'Fan On Na', 671.38);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (247, 'Yung Chi Ming', 906.23);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (248, 'Endo Rin', 482.33);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (249, 'Jose James', 949.80);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (250, 'Kwan Chi Ming', 70.08);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (251, 'Maeda Ayano', 678.44);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (252, 'Xiao Zhiyuan', 292.34);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (253, 'Marjorie Lee', 201.62);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (254, 'Nakamori Momoka', 628.11);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (255, 'Nakamura Daisuke', 786.43);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (256, 'Ono Tsubasa', 424.67);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (257, 'Yuen Wing Suen', 6.02);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (258, 'Barry Henry', 784.52);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (259, 'Abe Itsuki', 547.68);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (260, 'Sano Ryota', 319.54);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (261, 'Nakagawa Hikaru', 109.83);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (262, 'Gregory Moreno', 835.94);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (263, 'Jeff Torres', 658.77);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (264, 'Chan Wing Suen', 475.05);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (265, 'Kong Jialun', 242.63);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (266, 'Yamazaki Eita', 666.34);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (267, 'Edith Palmer', 218.28);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (268, 'Tong Chieh Lun', 729.31);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (269, 'Yau Kar Yan', 121.70);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (270, 'Brandon Gray', 676.55);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (271, 'Choi Chiu Wai', 734.55);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (272, 'Ng Chun Yu', 240.39);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (273, 'Jiang Lu', 774.19);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (274, 'Arimura Seiko', 980.69);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (275, 'Ernest Murray', 370.74);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (276, 'Martin Simmons', 237.69);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (277, 'Chang Ziyi', 837.32);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (278, 'Edith Sanchez', 585.42);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (279, 'Cheng Shihan', 930.38);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (280, 'Tang Kwok Kuen', 621.45);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (281, 'Takada Yuna', 82.32);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (282, 'Mok Chi Ming', 897.61);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (283, 'Danny Rose', 579.65);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (284, 'Nakayama Rin', 733.20);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (285, 'Miu Tin Wing', 436.21);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (286, 'Nakano Seiko', 47.80);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (287, 'Morita Tsubasa', 996.92);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (288, 'Matthew Hunter', 523.53);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (289, 'Chow Sau Man', 693.47);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (290, 'Aoki Sakura', 842.73);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (291, 'Vincent Daniels', 191.57);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (292, 'Nakagawa Yamato', 766.70);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (293, 'Saito Kazuma', 289.84);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (294, 'Lu Jiehong', 923.35);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (295, 'Mui Tsz Hin', 853.02);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (296, 'Au Ka Fai', 10.84);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (297, 'Wang Yunxi', 893.67);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (298, 'Liang Rui', 622.50);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (299, 'Abe Sakura', 853.90);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (300, 'Ikeda Airi', 80.17);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (301, 'Chris Tran', 429.13);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (302, 'Ma Ziyi', 897.16);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (303, 'Lok Sum Wing', 763.20);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (304, 'Huang Rui', 594.12);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (305, 'Yin Chi Yuen', 725.70);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (306, 'Shi Jiehong', 880.06);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (307, 'Grace Rice', 199.60);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (308, 'Dai Xiuying', 622.79);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (309, 'Hao Zitao', 293.24);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (310, 'Yung Sze Kwan', 352.70);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (311, 'Shi Ziyi', 308.00);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (312, 'Fan Ching Wan', 748.04);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (313, 'Endo Nanami', 945.87);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (314, 'So Wai Man', 767.93);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (315, 'Jesus Rice', 363.87);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (316, 'Lillian Romero', 110.63);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (317, 'Dai Wai Yee', 338.27);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (318, 'Randy Ward', 420.78);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (319, 'Liao Rui', 915.26);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (320, 'Cai Xiuying', 250.47);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (321, 'Tang Siu Wai', 376.96);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (322, 'Ono Ryota', 380.67);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (323, 'Su Jiehong', 479.07);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (324, 'Ye Shihan', 315.84);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (325, 'Shibata Ren', 274.74);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (326, 'Yau Lik Sun', 456.12);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (327, 'Cui Xiaoming', 694.45);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (328, 'Lu Yuning', 871.36);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (329, 'Lam Ka Ling', 362.58);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (330, 'Ku Chiu Wai', 731.82);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (331, 'Cho Chung Yin', 728.22);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (332, 'Mo Ming', 413.32);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (333, 'Teresa Bailey', 710.20);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (334, 'Tony Gonzales', 594.79);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (335, 'Sheila Sanchez', 248.33);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (336, 'Alfred Anderson', 871.15);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (337, 'Ogawa Kaito', 411.51);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (338, 'Sugawara Hina', 154.43);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (339, 'Jeffrey Morgan', 79.50);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (340, 'Harry Wright', 395.52);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (341, 'Frances Shaw', 620.47);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (342, 'Sit Kwok Kuen', 295.16);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (343, 'Emily Campbell', 872.38);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (344, 'Angela Campbell', 340.91);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (345, 'Au Tin Wing', 448.57);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (346, 'Zheng Zhennan', 451.87);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (347, 'Yan Lu', 673.51);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (348, 'Dong Yunxi', 528.99);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (349, 'Debbie Powell', 527.33);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (350, 'Fujii Takuya', 795.31);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (351, 'Saito Hikari', 291.47);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (352, 'Martin Palmer', 978.25);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (353, 'Fan Hiu Tung', 850.78);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (354, 'Wong Sze Yu', 4.14);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (355, 'Elaine Mitchell', 448.97);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (356, 'Chan Wai Man', 743.69);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (357, 'Ishida Hikari', 663.25);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (358, 'Xiong Rui', 999.39);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (359, 'Chin Cho Yee', 981.91);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (360, 'Lu Yunxi', 282.29);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (361, 'Tsang Ka Keung', 978.13);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (362, 'Ogawa Mio', 276.11);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (363, 'Shimada Kasumi', 976.06);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (364, 'Ishikawa Hana', 416.65);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (365, 'Irene Munoz', 275.26);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (366, 'Gong Xiuying', 243.49);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (367, 'Cheryl Robertson', 655.96);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (368, 'Ding Anqi', 178.26);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (369, 'Scott Stone', 252.92);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (370, 'Maria Gutierrez', 884.50);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (371, 'Alexander Boyd', 26.05);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (372, 'Yung Chun Yu', 792.54);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (373, 'Tian Ziyi', 776.72);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (374, 'Lai Ka Ling', 827.85);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (375, 'Takeda Yuto', 264.05);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (376, 'Tin Wai Han', 352.38);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (377, 'Yuen Chi Ming', 186.47);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (378, 'Takagi Kazuma', 459.54);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (379, 'Feng Jialun', 118.13);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (380, 'Matsumoto Shino', 829.91);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (381, 'Mui Tin Lok', 74.71);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (382, 'Ishikawa Rin', 24.59);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (383, 'Ye Jialun', 407.48);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (384, 'Miura Takuya', 351.19);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (385, 'Yip Wai Lam', 94.20);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (386, 'Chang Zhiyuan', 500.04);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (387, 'Matsumoto Airi', 396.21);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (388, 'Tse Ming', 663.31);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (389, 'Lee Chi Yuen', 749.34);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (390, 'Gao Shihan', 3.13);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (391, 'Chen Lu', 39.94);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (392, 'Shannon Ryan', 586.92);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (393, 'Bradley Hunt', 270.29);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (394, 'Cheng Tsz Hin', 38.69);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (395, 'Kimberly Robertson', 289.65);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (396, 'Wei Yuning', 415.42);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (397, 'Albert Griffin', 70.59);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (398, 'Francis Ellis', 334.99);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (399, 'Shawn Holmes', 103.46);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (400, 'He Jiehong', 159.53);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (401, 'Duan Ziyi', 398.63);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (402, 'Cho Chung Yin', 930.71);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (403, 'Nakajima Hazuki', 346.97);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (404, 'Phyllis Richardson', 359.19);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (405, 'Lok Wai Man', 606.00);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (406, 'Theodore Collins', 363.74);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (407, 'Diana Collins', 152.34);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (408, 'Zhu Lan', 961.94);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (409, 'Aoki Ayano', 306.22);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (410, 'Guo Yuning', 739.75);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (411, 'Annie Kennedy', 249.39);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (412, 'Ying Wai Lam', 293.17);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (413, 'Deng Jiehong', 820.83);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (414, 'Chan Hiu Tung', 450.30);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (415, 'Takahashi Itsuki', 729.78);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (416, 'Suzuki Akina', 407.80);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (417, 'Carol Nichols', 71.30);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (418, 'Ishikawa Seiko', 749.72);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (419, 'Huang Lan', 452.06);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (420, 'Bruce Gomez', 996.82);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (421, 'Zhong Xiuying', 982.23);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (422, 'Fan Siu Wai', 311.67);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (423, 'So Yu Ling', 306.90);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (424, 'Ruth Dunn', 729.92);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (425, 'Siu Sum Wing', 284.09);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (426, 'Nancy Russell', 877.78);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (427, 'Kao Wai Yee', 756.59);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (428, 'Peggy Brooks', 775.72);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (429, 'Sun Yunxi', 174.51);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (430, 'Philip Fox', 363.00);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (431, 'Wong Chun Yu', 478.93);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (432, 'Sakai Momoka', 662.02);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (433, 'Yu Zhiyuan', 591.23);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (434, 'Yu Jialun', 711.42);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (435, 'Kwong Wing Fat', 904.83);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (436, 'Meng Lu', 959.06);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (437, 'Mo Wai Man', 98.61);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (438, 'Jamie Hayes', 134.60);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (439, 'Koyama Ikki', 490.94);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (440, 'Yan Zitao', 389.63);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (441, 'Ishii Mai', 824.65);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (442, 'Lau Tin Lok', 460.01);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (443, 'Kao Chieh Lun', 809.39);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (444, 'Chiang Wai Man', 730.36);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (445, 'Nishimura Kenta', 64.73);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (446, 'Choi Wing Fat', 259.36);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (447, 'Lui Lai Yan', 990.93);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (448, 'Eric Kim', 139.69);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (449, 'Hashimoto Aoi', 838.04);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (450, 'Daniel Medina', 480.62);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (451, 'Nakamori Minato', 987.52);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (452, 'Russell Moreno', 955.18);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (453, 'Matsumoto Tsubasa', 714.90);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (454, 'Fan Kwok Kuen', 251.80);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (455, 'Han Lan', 994.95);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (456, 'Hayashi Kaito', 254.51);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (457, 'Ma Yuning', 615.47);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (458, 'Wu Xiuying', 786.62);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (459, 'Marie Rice', 569.94);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (460, 'Che Kwok Wing', 307.92);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (461, 'Watanabe Nanami', 294.45);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (462, 'Miu Cho Yee', 281.06);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (463, 'Sato Daichi', 872.93);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (464, 'Yung Wai Lam', 572.34);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (465, 'Danielle Thomas', 874.94);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (466, 'Phillip Henderson', 634.01);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (467, 'Yung Yu Ling', 46.70);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (468, 'Cho Sum Wing', 848.77);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (469, 'Lai Yu Ling', 741.88);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (470, 'Leonard Hayes', 523.12);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (471, 'Fukuda Daisuke', 259.12);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (472, 'Loui Sum Wing', 987.50);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (473, 'Chang On Na', 46.14);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (474, 'Imai Misaki', 979.07);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (475, 'Mok Wing Sze', 66.50);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (476, 'Yin Ka Man', 790.93);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (477, 'Man Wing Sze', 373.67);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (478, 'Siu Ka Ling', 642.49);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (479, 'Luo Ziyi', 190.39);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (480, 'George Bailey', 718.78);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (481, 'Zeng Lu', 546.04);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (482, 'Su Lu', 97.89);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (483, 'Guo Zhiyuan', 10.06);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (484, 'Yao Ziyi', 903.69);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (485, 'Chow Tin Lok', 430.86);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (486, 'Shimada Itsuki', 140.68);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (487, 'Otsuka Kasumi', 517.86);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (488, 'Lillian Ross', 743.43);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (489, 'Meng Lan', 363.09);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (490, 'Nishimura Yuto', 955.66);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (491, 'Sakai Nanami', 287.18);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (492, 'Lee Sau Man', 260.50);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (493, 'Michael Ellis', 366.58);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (494, 'Tian Zhiyuan', 983.75);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (495, 'Eugene Perry', 846.56);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (496, 'Zheng Yuning', 530.94);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (497, 'Dennis Clark', 882.56);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (498, 'Rita Sanchez', 334.11);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (499, 'Hao Jialun', 347.44);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (500, 'Annie Cooper', 173.46);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (501, 'Zhong Zitao', 477.40);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (502, 'Mike Fernandez', 87.91);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (503, 'Tse Kar Yan', 69.42);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (504, 'Wei Zhennan', 954.57);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (505, 'Sean Grant', 88.00);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (506, 'Gao Lu', 644.73);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (507, 'Carl Perry', 581.88);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (508, 'Lin Lu', 841.15);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (509, 'Wei Lan', 690.30);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (510, 'Kudo Aoshi', 905.41);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (511, 'Xia Lan', 234.96);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (512, 'Wu Wing Kuen', 552.20);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (513, 'Cai Lu', 625.61);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (514, 'Miyazaki Kasumi', 114.81);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (515, 'Howard Morales', 749.57);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (516, 'Loui On Na', 510.87);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (517, 'Zheng Rui', 458.25);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (518, 'Shimada Daisuke', 357.78);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (519, 'Manuel Myers', 316.00);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (520, 'Mo Rui', 436.86);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (521, 'Diana Hill', 585.94);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (522, 'Lu Anqi', 288.43);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (523, 'Cheng Xiaoming', 871.63);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (524, 'Roger Richardson', 139.53);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (525, 'Marjorie Harris', 100.02);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (526, 'Jose Carter', 123.81);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (527, 'Cho Wai Man', 421.59);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (528, 'Kobayashi Rena', 935.61);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (529, 'Feng Zhennan', 731.53);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (530, 'Maeda Sakura', 835.59);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (531, 'Song Zhiyuan', 268.99);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (532, 'Liang Shihan', 693.80);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (533, 'Tanaka Sakura', 243.36);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (534, 'Lu Zitao', 159.29);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (535, 'Kam Chiu Wai', 862.94);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (536, 'Chang Jiehong', 587.45);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (537, 'Tang Yuning', 593.44);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (538, 'Suzuki Mai', 149.67);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (539, 'Li Xiuying', 69.12);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (540, 'Luo Ziyi', 845.34);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (541, 'Cindy Snyder', 573.84);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (542, 'Luo Anqi', 763.81);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (543, 'Sun Jialun', 421.19);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (544, 'Tong Tin Lok', 942.02);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (545, 'Ng Tin Wing', 392.78);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (546, 'Pang Hiu Tung', 323.71);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (547, 'Jiang Zhiyuan', 640.15);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (548, 'Mui Wai San', 597.27);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (549, 'Julie Miller', 569.64);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (550, 'Guo Xiaoming', 936.07);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (551, 'Edith Martinez', 666.59);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (552, 'Nishimura Itsuki', 274.89);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (553, 'Mo Ka Man', 342.69);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (554, 'Choi Lik Sun', 500.01);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (555, 'Morita Rin', 377.98);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (556, 'Marie Allen', 982.87);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (557, 'Robert Ferguson', 117.66);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (558, 'Ku Wing Sze', 765.65);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (559, 'Fung Ho Yin', 955.73);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (560, 'Cindy Mills', 376.98);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (561, 'Kelly Hunter', 130.06);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (562, 'Wu Wai Man', 16.09);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (563, 'Shimada Sara', 346.47);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (564, 'Gloria Carter', 0.70);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (565, 'Willie Myers', 522.25);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (566, 'Zou Jiehong', 798.93);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (567, 'Barry Robertson', 58.99);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (568, 'Sugawara Momoka', 986.00);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (569, 'Phyllis Richardson', 120.02);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (570, 'Jin Anqi', 484.65);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (571, 'Sato Yuto', 102.35);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (572, 'Ruth Fernandez', 180.54);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (573, 'Kono Hina', 115.39);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (574, 'Lui Wing Suen', 679.95);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (575, 'Fang Lan', 485.74);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (576, 'Yin Jialun', 893.61);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (577, 'Sit Ching Wan', 865.02);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (578, 'Yamamoto Kaito', 637.49);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (579, 'Du Lu', 100.26);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (580, 'Wan Suk Yee', 220.10);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (581, 'Chad Morgan', 638.27);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (582, 'Sasaki Yuna', 158.34);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (583, 'Matsuda Yuna', 18.13);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (584, 'Ng Tak Wah', 702.25);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (585, 'Miura Rin', 990.54);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (586, 'Ho Ming Sze', 369.67);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (587, 'Xia Yuning', 277.45);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (588, 'Louis Fisher', 739.62);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (589, 'Chen Lan', 27.29);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (590, 'Rachel Ellis', 552.59);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (591, 'He Zitao', 570.94);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (592, 'Micheal Dunn', 481.93);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (593, 'Jiang Zhennan', 613.27);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (594, 'Yeow Tak Wah', 299.02);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (595, 'Long Rui', 459.05);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (596, 'Tang Lan', 281.50);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (597, 'Nishimura Eita', 537.00);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (598, 'Fong Ting Fung', 126.55);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (599, 'Alexander Alexander', 890.67);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (600, 'Lo Tsz Hin', 390.61);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (601, 'William Nguyen', 826.55);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (602, 'Virginia Ramirez', 540.43);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (603, 'Carmen Martinez', 196.61);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (604, 'Kenneth King', 151.51);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (605, 'Julia Patel', 660.39);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (606, 'Hsuan Wai Lam', 925.57);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (607, 'Lui On Na', 65.91);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (608, 'Sylvia Green', 234.98);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (609, 'Okada Mitsuki', 589.86);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (610, 'Takeuchi Yuito', 36.71);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (611, 'Ng Chi Yuen', 791.07);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (612, 'Alfred Simmons', 532.03);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (613, 'Jin Yuning', 646.19);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (614, 'Zhang Jialun', 387.24);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (615, 'Lin Jialun', 54.63);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (616, 'Yamada Kaito', 899.35);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (617, 'Phyllis Roberts', 832.20);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (618, 'Takeda Ryota', 686.44);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (619, 'Ichikawa Ayano', 733.34);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (620, 'Fan Hiu Tung', 817.80);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (621, 'Fan Zitao', 937.16);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (622, 'Li Ziyi', 78.34);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (623, 'Jane Foster', 450.61);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (624, 'Harry Gardner', 309.57);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (625, 'Hashimoto Ikki', 693.10);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (626, 'Mo Xiaoming', 968.25);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (627, 'Wada Ryota', 652.35);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (628, 'Ng Chi Yuen', 529.90);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (629, 'Jeff Weaver', 375.86);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (630, 'Judy Morgan', 520.14);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (631, 'Luo Zhiyuan', 469.52);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (632, 'Inoue Rin', 551.04);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (633, 'Joel Mason', 638.40);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (634, 'Zeng Yuning', 711.03);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (635, 'Xu Yunxi', 945.81);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (636, 'Koo Wai San', 310.89);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (637, 'Hayashi Shino', 891.48);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (638, 'Meng Wai Man', 77.56);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (639, 'Mo Yun Fat', 754.32);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (640, 'Josephine Hawkins', 648.39);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (641, 'Shing On Na', 394.64);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (642, 'Kong Zhennan', 572.98);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (643, 'Sano Nanami', 961.42);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (644, 'Hao Lu', 744.88);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (645, 'Uchida Hikaru', 288.76);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (646, 'Sun Shihan', 140.23);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (647, 'Jessica Henderson', 535.31);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (648, 'Cui Jiehong', 319.02);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (649, 'Cheng Lu', 984.39);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (650, 'Xiao Ziyi', 632.61);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (651, 'Feng Xiaoming', 398.75);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (652, 'Wei Rui', 588.06);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (653, 'Tamura Rin', 767.32);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (654, 'Hui Kwok Wing', 941.74);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (655, 'Yamashita Hina', 732.96);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (656, 'Cheng Wai Man', 117.56);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (657, 'Dale Scott', 130.83);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (658, 'Theresa Gutierrez', 503.36);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (659, 'Diana Silva', 849.41);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (660, 'Pak Sze Yu', 623.45);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (661, 'Yung Suk Yee', 764.06);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (662, 'Aaron Mcdonald', 843.79);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (663, 'Lin Lan', 901.34);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (664, 'Fang Ziyi', 984.40);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (665, 'Tamura Yamato', 166.31);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (666, 'Ota Mai', 323.72);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (667, 'Chang Wai Man', 85.25);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (668, 'Deng Yuning', 261.99);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (669, 'Kwan Sze Yu', 927.02);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (670, 'Yan Yunxi', 933.40);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (671, 'Xue Lu', 36.47);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (672, 'Miyazaki Momoe', 536.77);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (673, 'Song Jialun', 778.38);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (674, 'Ronald Hayes', 408.78);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (675, 'Hashimoto Hina', 740.88);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (676, 'Murata Momoka', 28.26);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (677, 'Amy Wood', 281.91);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (678, 'Lisa Nguyen', 917.15);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (679, 'Mak Sau Man', 384.81);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (680, 'Ishida Yuna', 709.77);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (681, 'Cao Lan', 18.74);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (682, 'Ichikawa Eita', 987.62);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (683, 'Sano Kazuma', 887.70);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (684, 'Hu Ziyi', 376.13);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (685, 'Phyllis Davis', 620.40);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (686, 'Tang Wing Sze', 470.97);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (687, 'Dong Yunxi', 464.85);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (688, 'Nakano Hikaru', 205.51);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (689, 'Yan Zitao', 360.66);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (690, 'Charlotte Mason', 188.67);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (691, 'Nishimura Seiko', 284.97);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (692, 'Francisco Garza', 276.45);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (693, 'Dale Ford', 36.95);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (694, 'Yamada Hazuki', 293.49);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (695, 'Mike Webb', 7.64);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (696, 'Hara Sakura', 730.91);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (697, 'Yamamoto Kaito', 389.46);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (698, 'Lu Yunxi', 97.00);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (699, 'Yamamoto Aoi', 373.02);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (700, 'Luo Anqi', 901.89);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (701, 'Heung Wing Suen', 184.18);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (702, 'Marcus Gardner', 955.58);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (703, 'Kwan Kwok Kuen', 472.22);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (704, 'Zou Ziyi', 813.30);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (705, 'Thelma Garcia', 533.97);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (706, 'Kono Kasumi', 828.18);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (707, 'Ronald Stone', 415.19);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (708, 'Miyamoto Riku', 492.06);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (709, 'Joel Dunn', 999.61);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (710, 'Jiang Xiaoming', 370.97);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (711, 'Ishii Sara', 323.45);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (712, 'Murakami Hana', 336.49);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (713, 'Edward Gibson', 438.75);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (714, 'Loui Kwok Wing', 594.03);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (715, 'Dong Yuning', 190.38);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (716, 'Meng Zhennan', 781.42);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (717, 'Okada Ikki', 618.06);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (718, 'Yoshida Yuito', 242.27);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (719, 'Doris Morris', 194.56);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (720, 'Patricia Walker', 59.22);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (721, 'Chin Suk Yee', 512.93);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (722, 'Yamamoto Mio', 873.67);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (723, 'Sugiyama Seiko', 771.92);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (724, 'Cui Xiuying', 923.30);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (725, 'Sasaki Hazuki', 0.31);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (726, 'Ricky Wagner', 970.63);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (727, 'Sara Turner', 194.24);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (728, 'Zheng Lan', 895.13);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (729, 'Otsuka Seiko', 368.82);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (730, 'Leslie Tucker', 823.94);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (731, 'Rosa Moore', 140.42);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (732, 'Jiang Yuning', 258.04);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (733, 'He Jialun', 287.72);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (734, 'Jiang Yunxi', 362.28);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (735, 'Miyamoto Airi', 620.81);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (736, 'Leung Chi Ming', 993.74);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (737, 'Alfred Torres', 261.47);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (738, 'Eric Boyd', 607.95);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (739, 'Gao Zhennan', 152.71);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (740, 'Xiao Lu', 946.71);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (741, 'Martin Payne', 300.60);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (742, 'Takagi Ren', 717.19);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (743, 'Chung Ming Sze', 30.45);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (744, 'Howard Medina', 800.37);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (745, 'Chin Sum Wing', 409.60);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (746, 'Kong Ka Man', 345.35);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (747, 'Jin Lu', 576.02);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (748, 'Tao Zitao', 546.85);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (749, 'Ying Tak Wah', 250.06);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (750, 'Wong Chieh Lun', 873.82);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (751, 'He Jiehong', 158.03);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (752, 'Wang Zhiyuan', 714.44);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (753, 'Ho Hok Yau', 730.96);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (754, 'Qian Xiaoming', 815.36);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (755, 'Ma Shihan', 238.35);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (756, 'Hou Xiaoming', 947.56);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (757, 'Wong Wing Suen', 254.39);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (758, 'Liu Rui', 199.46);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (759, 'Xie Lan', 79.48);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (760, 'Mok Kwok Kuen', 70.13);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (761, 'Kong Cho Yee', 513.72);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (762, 'Leung Ka Keung', 200.91);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (763, 'Travis Wells', 858.80);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (764, 'Yan Lu', 782.34);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (765, 'Christina Gordon', 34.85);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (766, 'Ono Takuya', 175.68);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (767, 'Yan Yuning', 471.30);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (768, 'Yamaguchi Sakura', 499.88);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (769, 'Sasaki Seiko', 871.05);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (770, 'Virginia Nguyen', 992.74);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (771, 'Louise Moreno', 724.63);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (772, 'Tian Xiuying', 478.96);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (773, 'Shao Zhennan', 320.16);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (774, 'Patrick Henderson', 764.51);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (775, 'Fang Shihan', 28.80);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (776, 'Hu Shihan', 335.78);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (777, 'Hou Jialun', 67.34);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (778, 'Ishii Eita', 341.02);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (779, 'Fong Suk Yee', 441.03);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (780, 'Gao Anqi', 246.38);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (781, 'Theodore Patel', 195.24);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (782, 'Jin Xiaoming', 271.78);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (783, 'Fukuda Hikaru', 516.67);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (784, 'Takagi Shino', 497.48);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (785, 'Sugiyama Kazuma', 398.27);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (786, 'Tanaka Yuito', 970.44);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (787, 'Tan Lu', 517.62);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (788, 'Huang Lan', 324.83);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (789, 'Wu Lan', 836.45);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (790, 'Ronald Jenkins', 963.19);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (791, 'Tang Rui', 75.02);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (792, 'Shao Zitao', 864.77);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (793, 'Mao Anqi', 304.36);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (794, 'Siu Ka Man', 622.47);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (795, 'Pak Hui Mei', 65.21);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (796, 'Richard Hall', 492.26);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (797, 'Ren Xiuying', 875.02);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (798, 'Hashimoto Aoi', 360.76);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (799, 'Meng Tin Lok', 863.34);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (800, 'Tam Wing Fat', 902.80);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (801, 'Mo Ming', 732.43);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (802, 'Kudo Ayano', 967.47);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (803, 'Willie Tran', 325.08);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (804, 'Yao Ziyi', 121.65);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (805, 'Dong Jialun', 831.12);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (806, 'Catherine Freeman', 310.46);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (807, 'Fu Kwok Wing', 498.23);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (808, 'Yao Jialun', 275.48);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (809, 'Nakamori Mai', 607.01);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (810, 'Nakamori Aoi', 462.99);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (811, 'Kojima Kasumi', 112.90);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (812, 'Koo Ka Fai', 899.31);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (813, 'Clara Johnson', 420.41);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (814, 'Zou Zhiyuan', 328.80);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (815, 'Fan Ziyi', 658.19);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (816, 'Hara Hazuki', 890.92);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (817, 'Nakagawa Yuna', 814.53);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (818, 'Masuda Minato', 77.19);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (819, 'Ding Jialun', 493.73);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (820, 'Judith Palmer', 821.22);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (821, 'Yung Hok Yau', 171.71);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (822, 'Tong Chiu Wai', 471.49);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (823, 'Zhou Anqi', 976.10);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (824, 'Liao Fu Shing', 369.03);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (825, 'Matsuda Hazuki', 167.93);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (826, 'Miyazaki Kenta', 575.81);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (827, 'Sato Hikari', 571.68);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (828, 'Tong Hui Mei', 862.29);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (829, 'Tam Hui Mei', 137.56);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (830, 'Justin Crawford', 848.03);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (831, 'John Henderson', 206.10);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (832, 'Takeuchi Misaki', 74.83);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (833, 'Mildred Nguyen', 624.15);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (834, 'Nakamura Rin', 129.27);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (835, 'Otsuka Yuna', 857.03);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (836, 'Pang Tsz Ching', 632.99);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (837, 'Yan Jialun', 219.87);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (838, 'Arimura Yuito', 360.55);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (839, 'Tong Hok Yau', 327.66);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (840, 'Chiba Misaki', 914.42);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (841, 'Cao Xiuying', 946.78);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (842, 'Deborah Morales', 160.00);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (843, 'Fong Ming Sze', 82.52);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (844, 'Hui Yu Ling', 293.03);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (845, 'Nakajima Kasumi', 42.92);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (846, 'Dong Yuning', 879.40);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (847, 'Zhao Ziyi', 82.01);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (848, 'Hasegawa Seiko', 18.88);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (849, 'Kathryn Hall', 98.87);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (850, 'Watanabe Sakura', 39.73);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (851, 'Connie Nelson', 680.17);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (852, 'Nakamori Akina', 122.43);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (853, 'Janet Meyer', 698.14);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (854, 'Cheung Cho Yee', 636.67);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (855, 'Yung Cho Yee', 305.05);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (856, 'Yamashita Hana', 688.28);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (857, 'Wu Jialun', 824.19);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (858, 'Rose Snyder', 572.09);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (859, 'Ishii Aoi', 323.35);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (860, 'Fu Tak Wah', 434.94);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (861, 'Jerry Barnes', 457.52);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (862, 'Dong Zhennan', 942.08);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (863, 'Masuda Yuito', 643.16);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (864, 'Nakamura Daisuke', 67.83);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (865, 'Christine Ford', 117.19);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (866, 'Ono Kaito', 291.71);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (867, 'Pauline Schmidt', 585.15);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (868, 'Jia Ziyi', 464.12);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (869, 'Kam Lik Sun', 967.31);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (870, 'Jiang Yuning', 91.31);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (871, 'Tian Jialun', 581.47);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (872, 'Ralph Gordon', 409.77);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (873, 'Xu Ziyi', 856.40);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (874, 'Miyamoto Yuto', 336.79);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (875, 'Shimada Shino', 835.23);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (876, 'Yan Yunxi', 596.36);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (877, 'Timothy Stone', 863.97);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (878, 'Ray Dunn', 175.36);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (879, 'Yeung Wing Fat', 906.43);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (880, 'Alexander Mcdonald', 771.96);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (881, 'Ding Yunxi', 504.28);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (882, 'Koo Sum Wing', 49.90);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (883, 'Carolyn Patel', 616.10);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (884, 'Terry Harrison', 955.95);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (885, 'Travis Murray', 484.67);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (886, 'Janice Gomez', 968.53);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (887, 'Hara Daichi', 817.98);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (888, 'Sakai Momoe', 266.94);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (889, 'Lam Sum Wing', 622.26);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (890, 'Carol Gonzalez', 106.24);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (891, 'Huang Xiuying', 790.71);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (892, 'Eddie Aguilar', 292.67);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (893, 'Xia Ziyi', 830.43);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (894, 'Choi Yu Ling', 611.98);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (895, 'Yoshida Eita', 477.95);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (896, 'Chad Holmes', 622.50);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (897, 'Shimizu Kazuma', 982.90);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (898, 'Diane Rice', 818.27);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (899, 'Sasaki Mai', 529.17);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (900, 'Kwok Sze Yu', 991.41);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (901, 'Wang Jialun', 728.89);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (902, 'Frederick Walker', 90.93);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (903, 'Fujii Daichi', 831.52);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (904, 'Chic Sze Kwan', 339.23);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (905, 'Donna Kelley', 792.39);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (906, 'Jesse Williams', 660.32);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (907, 'Jiang Lu', 884.79);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (908, 'Ono Ren', 63.37);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (909, 'Sandra Marshall', 491.04);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (910, 'Imai Akina', 926.18);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (911, 'Sugiyama Itsuki', 225.13);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (912, 'George Hill', 434.21);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (913, 'Shing Ka Fai', 793.39);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (914, 'Patricia Jordan', 792.47);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (915, 'Manuel Wagner', 883.73);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (916, 'Xie Zitao', 463.36);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (917, 'Sylvia Brown', 758.49);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (918, 'Fong Chi Ming', 392.32);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (919, 'Chang Hui Mei', 514.34);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (920, 'Hui Hiu Tung', 477.00);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (921, 'Wada Aoshi', 357.40);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (922, 'Ying On Kay', 427.62);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (923, 'Xu Zhiyuan', 826.49);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (924, 'Valerie Rogers', 146.68);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (925, 'Ito Itsuki', 883.76);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (926, 'Tsui Ling Ling', 763.33);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (927, 'Ma Lik Sun', 959.94);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (928, 'Lui Wing Sze', 235.86);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (929, 'Ishii Takuya', 155.50);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (930, 'Hui Ka Ling', 271.92);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (931, 'Ku Wai Man', 934.38);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (932, 'Liang Anqi', 491.27);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (933, 'Chen Xiuying', 570.63);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (934, 'Dai Ting Fung', 848.25);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (935, 'Carl Garza', 7.09);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (936, 'Kwong Chun Yu', 921.03);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (937, 'Lo Wai Yee', 500.44);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (938, 'Jennifer Martin', 209.38);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (939, 'Shing Wing Sze', 118.67);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (940, 'Wada Rena', 23.80);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (941, 'Saito Daichi', 714.74);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (942, 'Tong Ka Keung', 13.50);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (943, 'Francis Carter', 59.38);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (944, 'He Zhiyuan', 490.60);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (945, 'Vincent Hughes', 152.65);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (946, 'Man Ming', 411.05);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (947, 'Masuda Ayano', 389.35);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (948, 'Sano Hazuki', 566.00);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (949, 'Victor Palmer', 185.04);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (950, 'Lee Hiu Tung', 754.58);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (951, 'Matsuda Seiko', 570.87);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (952, 'Masuda Rena', 809.40);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (953, 'Shimizu Yuna', 962.86);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (954, 'Sugiyama Riku', 17.04);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (955, 'Sasaki Ren', 641.14);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (956, 'Hsuan Wing Suen', 954.27);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (957, 'Song Rui', 291.13);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (958, 'Yam Sau Man', 957.02);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (959, 'He Zhennan', 95.31);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (960, 'Suzuki Airi', 341.84);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (961, 'Ding Xiuying', 847.08);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (962, 'Fujita Kenta', 123.17);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (963, 'Choi Ka Keung', 52.80);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (964, 'Chang Jiehong', 781.00);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (965, 'Lam Sai Wing', 360.05);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (966, 'Iwasaki Yamato', 281.97);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (967, 'Jane Allen', 668.41);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (968, 'Ueda Mai', 360.61);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (969, 'Mo Xiuying', 823.89);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (970, 'Jacob Olson', 219.70);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (971, 'Gong Lu', 723.45);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (972, 'Kimura Hina', 72.82);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (973, 'Sakamoto Airi', 877.10);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (974, 'Lu Yunxi', 315.16);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (975, 'Wei Ziyi', 237.75);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (976, 'Tamura Airi', 297.96);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (977, 'Yu Xiaoming', 546.36);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (978, 'Leung Wai Man', 785.29);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (979, 'Janice Campbell', 544.39);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (980, 'Yamazaki Riku', 881.19);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (981, 'Leung Ka Ling', 203.26);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (982, 'Hashimoto Tsubasa', 143.82);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (983, 'Hasegawa Yuna', 134.39);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (984, 'Wu Lan', 399.63);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (985, 'Nakamori Airi', 518.93);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (986, 'Walter Hunt', 558.51);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (987, 'Tse Suk Yee', 717.66);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (988, 'Li Xiaoming', 814.40);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (989, 'Zhang Rui', 725.38);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (990, 'Ma Tin Wing', 312.31);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (991, 'Julie Smith', 635.91);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (992, 'Jia Lu', 977.12);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (993, 'Lisa Hicks', 942.81);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (994, 'Alan Hicks', 40.14);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (995, 'Amy Salazar', 852.18);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (996, 'Morita Seiko', 659.40);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (997, 'Tong Kar Yan', 43.60);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (998, 'Imai Rena', 731.62);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (999, 'Che Sau Man', 384.87);
INSERT INTO `users` (`id`, `name`, `credit`) VALUES (1000, 'Mary Mason', 700.43);
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
